### ISSUE TITLE
Issues with CI Label 

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/continuous-integration#22]
Hey Mike, 
The CI label from your page shows the test failing, but when I cloned and solved the problem and updated on my forked repo, I wondered if it should itself update to test passing or we need to take some steps to make that change. Plus, I was able to change mine in actions to neutral. Is that the way to go about it? Thanks.

**Comment by mikeizbicki** [comment]
I've replied to your question in the main class repo at <https://github.com/mikeizbicki/cmc-csci143/issues/96>.  Moving the question there just ensures that more people are likely to see it.
