### ISSUE TITLE
Only tests 3.6 is failing

### ISSUE THREAD

**Issue by deriksuria** [mikeizbicki/continuous-integration#29]
So far tests 3.7, 3.8, and 3.9 are correct. However, I am running into an issue for tests 3.6, specifically the **set up Python 3.6** step. I've been searching online and haven't found a way to fix this- any help is appreciated! Thanks!

<img width="1404" alt="Screen Shot 2023-01-23 at 2 24 04 PM" src="https://user-images.githubusercontent.com/89935741/214163864-a3087f41-e842-4fb4-a0b7-2bfa4d8ca5aa.png">

**Comment by tennisoctocat** [comment]
I had this problem too. It looks like Mike just removed 3.6 from the Python versions to be checked against and that @finnless is working on another fix according to this [pull request](https://github.com/mikeizbicki/continuous-integration/pull/28).

Edit: Here's Mike's [response](https://github.com/mikeizbicki/cmc-csci143/issues/228) to another student who encountered this problem.
