### ISSUE TITLE
Where should we submit our Github link on Sakai?

### ISSUE THREAD

**Issue by deriksuria** [mikeizbicki/continuous-integration#33]
My submission is currently in the drop box since there were no assignments. Should I submit it here or somewhere else on Sakai?

<img width="1216" alt="Screen Shot 2023-01-23 at 7 22 05 PM" src="https://user-images.githubusercontent.com/89935741/214205942-44d8ae0b-33ba-4adf-a64d-fcf767813ae7.png">

**Comment by mikeizbicki** [comment]
I think you might be looking in the lab sakai page instead of the main class sakai page.  We won't be using the lab pages at all in this class, and the main class page has an assignment submission.
