### ISSUE TITLE
Big Data student who took Data Structures

### ISSUE THREAD

**Issue by irajmoradi** [mikeizbicki/continuous-integration#42]
Hello,

When I try forking this repo it doesn't automatically work since I already have a fork of this repo from when I took data structures. Should I delete the old fork of this assignment and make a new one for big data and do the assignment, or just turn in the fork I have from data structures, or rename the old fork and create a new fork?

Sincerely,
Iraj James Moradi

**Comment by mikeizbicki** [comment]
Let's repost this to the class repo, where everyone will be able to see the question/answer.
